services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in / available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    #    Arkounay\Bundle\QuickAdminGeneratorBundle\:
    #        resource: '../../*'
    #        exclude: '../../{DependencyInjection,Tests}'

    Arkounay\Bundle\QuickAdminGeneratorBundle\Extension\FieldService:
        autowire: true
        arguments:
            $formRenderer: '@twig.form.renderer'

    Arkounay\Bundle\QuickAdminGeneratorBundle\Extension\TwigLoaderService:
        autowire: true

    Arkounay\Bundle\QuickAdminGeneratorBundle\Crud\CrudListener:
        autowire: true

    Arkounay\Bundle\QuickAdminGeneratorBundle\EventSubscriber\ControllerSubscriber:
        autowire: true
        autoconfigure: true

    Arkounay\Bundle\QuickAdminGeneratorBundle\Menu\Menu:
        arguments:
            $cruds: !tagged_iterator quickadmin.crud
            $config: '%quick_admin_generator%'

    Arkounay\Bundle\QuickAdminGeneratorBundle\Menu\MenuInterface: '@Arkounay\Bundle\QuickAdminGeneratorBundle\Menu\Menu'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Arkounay\Bundle\QuickAdminGeneratorBundle\Controller\DashboardController:
        arguments:
            $config: '%quick_admin_generator%'
        tags: ['controller.service_arguments']

    Arkounay\Bundle\QuickAdminGeneratorBundle\Controller\GlobalSearchController:
        arguments:
            $cruds: !tagged_iterator quickadmin.crud
        tags: ['controller.service_arguments']

    Arkounay\Bundle\QuickAdminGeneratorBundle\Controller\ThemeController:
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Arkounay\Bundle\QuickAdminGeneratorBundle\Twig\Extension\QagExtension:
        tags:
            - 'twig.extension'

    Arkounay\Bundle\QuickAdminGeneratorBundle\Twig\Runtime\QagExtensionRuntime:
        arguments:
            $config: '%quick_admin_generator%'

    Arkounay\Bundle\QuickAdminGeneratorBundle\Crud\RouteLoader:
        arguments:
            - !tagged_iterator quickadmin.crud
            - '%quick_admin_generator%'

    Arkounay\Bundle\QuickAdminGeneratorBundle\Command\QagTwigCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $cruds: !tagged_iterator quickadmin.crud
        autowire: true