language: php
cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.4
        - php: 7.2
        - php: 7.3
        - php: nightly

    allow_failures:
        - php: nightly

install:
    - composer update $COMPOSER_FLAGS --no-interaction

script:
    - phpunit