language: php
cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - XDEBUG_MODE=coverage

matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: 8.0
        - php: nightly

    allow_failures:
        - php: nightly

install:
    - composer update $COMPOSER_FLAGS --no-interaction

script:
    - phpunit --coverage-clover coverage.xml

after_success:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov