coverage:
    precision: 2
    round: down
    status:
        project:
            default:
                threshold: 3%
                if_not_found: success
        patch:
            default:
                enabled: no
                threshold: 8%
                if_not_found: success
        changes:
            default:
                enabled: no
                if_not_found: success