# OS: Linux; Symfony: latest stable; PHP: all the commonly used versions supported by this bundle
name: "Tests - Linux"

on: push
env:
    fail-fast: true

jobs:
    tests:
        name: "PHP ${{ matrix.php-version }}"
        runs-on: 'ubuntu-latest'
        continue-on-error: false
        strategy:
            matrix:
                php-version: ['8.0', '8.1']
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v2.3.3

            - name: 'Install PHP with extensions'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: xdebug
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2
                  extensions: mbstring, intl
                  ini-values: date.timezone=UTC

            - name: 'Install project dependencies'
              run: |
                  composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable
                  vendor/bin/simple-phpunit install
            - name: 'Run tests'
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'max[indirect]=10&max[total]=27'
              run: vendor/bin/phpunit --coverage-clover coverage.xml

            - name: Codecov
              uses: codecov/codecov-action@v2